using GoldsrcNetClient.Core.Protocol;

namespace GoldsrcNetClient.Core.Delta;

public static class DeltaDefinitions
{
    public static readonly DeltaType Event = new("event_t", 0x0E, [
        new("entindex", DeltaFieldFlag.Integer, 10, 1.0f),
        new("bparam1", DeltaFieldFlag.Integer, 1, 1.0f),
        new("bparam2", DeltaFieldFlag.Integer, 1, 1.0f),
        new("origin[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("origin[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("origin[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("fparam1", DeltaFieldFlag.Float | DeltaFieldFlag.Signed, 20, 100.0f),
        new("fparam2", DeltaFieldFlag.Float | DeltaFieldFlag.Signed, 20, 100.0f),
        new("iparam1", DeltaFieldFlag.Integer | DeltaFieldFlag.Signed, 16, 1.0f),
        new("iparam2", DeltaFieldFlag.Integer | DeltaFieldFlag.Signed, 16, 1.0f),
        new("angles[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("angles[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("angles[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("ducking", DeltaFieldFlag.Integer, 1, 1.0f),
    ]);

    public static readonly DeltaType WeaponData = new("weapon_data_t", 0x14, [
        new("m_flTimeWeaponIdle", DeltaFieldFlag.Float | DeltaFieldFlag.Signed, 22, 1000.0f),
        new("m_flNextPrimaryAttack", DeltaFieldFlag.Float | DeltaFieldFlag.Signed, 22, 1000.0f),
        new("m_flNextReload", DeltaFieldFlag.Float | DeltaFieldFlag.Signed, 22, 1000.0f),
        new("m_fNextAimBonus", DeltaFieldFlag.Float | DeltaFieldFlag.Signed, 22, 1000.0f),
        new("m_flNextSecondaryAttack", DeltaFieldFlag.Float | DeltaFieldFlag.Signed, 22, 1000.0f),
        new("m_iClip", DeltaFieldFlag.Signed | DeltaFieldFlag.Integer, 10, 1.0f),
        new("m_flPumpTime", DeltaFieldFlag.Float | DeltaFieldFlag.Signed, 22, 1000.0f),
        new("m_fInSpecialReload", DeltaFieldFlag.Integer, 2, 1.0f),
        new("m_fReloadTime", DeltaFieldFlag.Float, 16, 100.0f),
        new("m_fInReload", DeltaFieldFlag.Integer, 1, 1.0f),
        new("m_fAimedDamage", DeltaFieldFlag.Float, 6, 0.1f),
        new("m_fInZoom", DeltaFieldFlag.Integer, 1, 1.0f),
        new("m_iWeaponState", DeltaFieldFlag.Integer, 2, 1.0f),
        new("m_iId", DeltaFieldFlag.Integer, 5, 1.0f),
        new("iuser1", DeltaFieldFlag.Signed | DeltaFieldFlag.Integer, 10, 1.0f),
        new("iuser2", DeltaFieldFlag.Signed | DeltaFieldFlag.Integer, 10, 1.0f),
        new("iuser3", DeltaFieldFlag.Signed | DeltaFieldFlag.Integer, 10, 1.0f),
        new("fuser1", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 22, 1000.0f),
        new("fuser2", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 22, 128.0f),
        new("fuser3", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 22, 128.0f),
    ]);

    public static readonly DeltaType UserCmd = new("usercmd_t", 0x0F, [
        new("lerp_msec", DeltaFieldFlag.Short, 9, 1.0f),
        new("msec", DeltaFieldFlag.Byte, 8, 1.0f),
        new("viewangles[1]", DeltaFieldFlag.Angle, 16, 1.0f),
        new("viewangles[0]", DeltaFieldFlag.Angle, 16, 1.0f),
        new("buttons", DeltaFieldFlag.Short, 16, 1.0f),
        new("forwardmove", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 12, 1.0f),
        new("lightlevel", DeltaFieldFlag.Byte, 8, 1.0f),
        new("sidemove", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 12, 1.0f),
        new("upmove", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 12, 1.0f),
        new("impulse", DeltaFieldFlag.Byte, 8, 1.0f),
        new("viewangles[2]", DeltaFieldFlag.Angle, 16, 1.0f),
        new("impact_index", DeltaFieldFlag.Integer, 6, 1.0f),
        new("impact_position[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("impact_position[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("impact_position[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
    ]);

    public static readonly DeltaType CustomEntityState = new("custom_entity_state_t", 0x13, [
        new("rendermode", DeltaFieldFlag.Integer, 8, 1.0f),
        new("origin[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 17, 8.0f),
        new("origin[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 17, 8.0f),
        new("origin[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 17, 8.0f),
        new("angles[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 17, 8.0f),
        new("angles[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 17, 8.0f),
        new("angles[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 17, 8.0f),
        new("sequence", DeltaFieldFlag.Integer, 16, 1.0f),
        new("skin", DeltaFieldFlag.Integer, 16, 1.0f),
        new("modelindex", DeltaFieldFlag.Integer, 16, 1.0f),
        new("scale", DeltaFieldFlag.Float, 8, 1.0f),
        new("body", DeltaFieldFlag.Integer, 8, 1.0f),
        new("rendercolor.r", DeltaFieldFlag.Byte, 8, 1.0f),
        new("rendercolor.g", DeltaFieldFlag.Byte, 8, 1.0f),
        new("rendercolor.b", DeltaFieldFlag.Byte, 8, 1.0f),
        new("renderfx", DeltaFieldFlag.Integer, 8, 1.0f),
        new("renderamt", DeltaFieldFlag.Integer, 8, 1.0f),
        new("frame", DeltaFieldFlag.Float, 8, 1.0f),
        new("animtime", DeltaFieldFlag.Float, 8, 1.0f),
    ]);

    public static readonly DeltaType EntityStatePlayer = new("entity_state_player_t", 0x31, [
        new("animtime", DeltaFieldFlag.TimeWindow8, 8, 1.0f),
        new("frame", DeltaFieldFlag.Float, 8, 1.0f),
        new("origin[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 18, 32.0f),
        new("angles[0]", DeltaFieldFlag.Angle, 16, 1.0f),
        new("angles[1]", DeltaFieldFlag.Angle, 16, 1.0f),
        new("origin[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 18, 32.0f),
        new("origin[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 18, 32.0f),
        new("gaitsequence", DeltaFieldFlag.Integer, 8, 1.0f),
        new("sequence", DeltaFieldFlag.Integer, 8, 1.0f),
        new("modelindex", DeltaFieldFlag.Integer, 10, 1.0f),
        new("movetype", DeltaFieldFlag.Integer, 4, 1.0f),
        new("solid", DeltaFieldFlag.Short, 3, 1.0f),
        new("mins[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("mins[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("mins[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("maxs[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("maxs[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("maxs[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("weaponmodel", DeltaFieldFlag.Integer, 10, 1.0f),
        new("team", DeltaFieldFlag.Integer, 4, 1.0f),
        new("playerclass", DeltaFieldFlag.Integer, 4, 1.0f),
        new("owner", DeltaFieldFlag.Integer, 5, 1.0f),
        new("effects", DeltaFieldFlag.Integer, 8, 1.0f),
        new("angles[2]", DeltaFieldFlag.Angle, 16, 1.0f),
        new("colormap", DeltaFieldFlag.Integer, 16, 1.0f),
        new("framerate", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 8, 16.0f),
        new("skin", DeltaFieldFlag.Short | DeltaFieldFlag.Signed, 9, 1.0f),
        new("controller[0]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("controller[1]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("controller[2]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("controller[3]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("blending[0]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("blending[1]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("body", DeltaFieldFlag.Integer, 8, 1.0f),
        new("rendermode", DeltaFieldFlag.Integer, 8, 1.0f),
        new("renderamt", DeltaFieldFlag.Integer, 8, 1.0f),
        new("renderfx", DeltaFieldFlag.Integer, 8, 1.0f),
        new("scale", DeltaFieldFlag.Float, 16, 256.0f),
        new("rendercolor.r", DeltaFieldFlag.Byte, 8, 1.0f),
        new("rendercolor.g", DeltaFieldFlag.Byte, 8, 1.0f),
        new("rendercolor.b", DeltaFieldFlag.Byte, 8, 1.0f),
        new("friction", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("usehull", DeltaFieldFlag.Integer, 1, 1.0f),
        new("gravity", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 32.0f),
        new("aiment", DeltaFieldFlag.Integer, 11, 1.0f),
        new("basevelocity[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("basevelocity[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("basevelocity[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("spectator", DeltaFieldFlag.Integer, 1, 1.0f),
    ]);

    public static readonly DeltaType EntityState = new("entity_state_t", 0x34, [
        new("animtime", DeltaFieldFlag.TimeWindow8, 8, 1.0f),
        new("frame", DeltaFieldFlag.Float, 10, 4.0f),
        new("origin[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("angles[0]", DeltaFieldFlag.Angle, 16, 1.0f),
        new("angles[1]", DeltaFieldFlag.Angle, 16, 1.0f),
        new("origin[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("origin[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("sequence", DeltaFieldFlag.Integer, 8, 1.0f),
        new("modelindex", DeltaFieldFlag.Integer, 10, 1.0f),
        new("movetype", DeltaFieldFlag.Integer, 4, 1.0f),
        new("solid", DeltaFieldFlag.Short, 3, 1.0f),
        new("mins[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("mins[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("mins[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("maxs[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("maxs[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("maxs[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("endpos[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 13, 1.0f),
        new("endpos[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 13, 1.0f),
        new("endpos[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 13, 1.0f),
        new("startpos[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 13, 1.0f),
        new("startpos[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 13, 1.0f),
        new("startpos[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 13, 1.0f),
        new("impacttime", DeltaFieldFlag.TimeWindowBig, 13, 100.0f),
        new("starttime", DeltaFieldFlag.TimeWindowBig, 13, 100.0f),
        new("weaponmodel", DeltaFieldFlag.Integer, 10, 1.0f),
        new("owner", DeltaFieldFlag.Integer, 5, 1.0f),
        new("effects", DeltaFieldFlag.Integer, 8, 1.0f),
        new("eflags", DeltaFieldFlag.Integer, 1, 1.0f),
        new("angles[2]", DeltaFieldFlag.Angle, 16, 1.0f),
        new("colormap", DeltaFieldFlag.Integer, 16, 1.0f),
        new("framerate", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 8, 16.0f),
        new("skin", DeltaFieldFlag.Short | DeltaFieldFlag.Signed, 9, 1.0f),
        new("controller[0]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("controller[1]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("controller[2]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("controller[3]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("blending[0]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("blending[1]", DeltaFieldFlag.Byte, 8, 1.0f),
        new("body", DeltaFieldFlag.Integer, 8, 1.0f),
        new("rendermode", DeltaFieldFlag.Integer, 8, 1.0f),
        new("renderamt", DeltaFieldFlag.Integer, 8, 1.0f),
        new("renderfx", DeltaFieldFlag.Integer, 8, 1.0f),
        new("scale", DeltaFieldFlag.Float, 16, 256.0f),
        new("rendercolor.r", DeltaFieldFlag.Byte, 8, 1.0f),
        new("rendercolor.g", DeltaFieldFlag.Byte, 8, 1.0f),
        new("rendercolor.b", DeltaFieldFlag.Byte, 8, 1.0f),
        new("aiment", DeltaFieldFlag.Integer, 11, 1.0f),
        new("basevelocity[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("basevelocity[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("basevelocity[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("playerclass", DeltaFieldFlag.Integer, 1, 1.0f),
    ]);

    public static readonly DeltaType ClientData = new("clientdata_t", 0x32, [
        new("flTimeStepSound", DeltaFieldFlag.Integer, 10, 1.0f),
        new("origin[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 21, 128.0f),
        new("origin[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 21, 128.0f),
        new("velocity[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("velocity[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("m_flNextAttack", DeltaFieldFlag.Float | DeltaFieldFlag.Signed, 22, 1000.0f),
        new("origin[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 21, 128.0f),
        new("velocity[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("ammo_nails", DeltaFieldFlag.Signed | DeltaFieldFlag.Integer, 10, 1.0f),
        new("ammo_shells", DeltaFieldFlag.Signed | DeltaFieldFlag.Integer, 10, 1.0f),
        new("ammo_cells", DeltaFieldFlag.Signed | DeltaFieldFlag.Integer, 10, 1.0f),
        new("ammo_rockets", DeltaFieldFlag.Signed | DeltaFieldFlag.Integer, 10, 1.0f),
        new("m_iId", DeltaFieldFlag.Integer, 5, 1.0f),
        new("punchangle[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("flags", DeltaFieldFlag.Integer, 32, 1.0f),
        new("weaponanim", DeltaFieldFlag.Integer, 8, 1.0f),
        new("health", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("maxspeed", DeltaFieldFlag.Float, 16, 10.0f),
        new("flDuckTime", DeltaFieldFlag.Integer, 10, 1.0f),
        new("view_ofs[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 4.0f),
        new("punchangle[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("punchangle[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 16, 8.0f),
        new("viewmodel", DeltaFieldFlag.Integer, 10, 1.0f),
        new("weapons", DeltaFieldFlag.Integer, 32, 1.0f),
        new("pushmsec", DeltaFieldFlag.Integer, 11, 1.0f),
        new("deadflag", DeltaFieldFlag.Integer, 3, 1.0f),
        new("fov", DeltaFieldFlag.Float, 8, 1.0f),
        new("physinfo", DeltaFieldFlag.StringField, 1, 1.0f),
        new("bInDuck", DeltaFieldFlag.Integer, 1, 1.0f),
        new("flSwimTime", DeltaFieldFlag.Integer, 10, 1.0f),
        new("waterjumptime", DeltaFieldFlag.Integer, 15, 1.0f),
        new("waterlevel", DeltaFieldFlag.Integer, 2, 1.0f),
        new("iuser1", DeltaFieldFlag.Integer, 5, 1.0f),
        new("iuser2", DeltaFieldFlag.Integer, 5, 1.0f),
        new("vuser1[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser1[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser1[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser2[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser2[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser2[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser3[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser3[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser3[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser4[0]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser4[1]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("vuser4[2]", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 1.0f),
        new("fuser1", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 22, 128.0f),
        new("fuser2", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 128.0f),
        new("fuser3", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 10, 128.0f),
        new("fuser4", DeltaFieldFlag.Signed | DeltaFieldFlag.Float, 2, 128.0f),
    ]);

    public static readonly DeltaType[] All = [Event, WeaponData, UserCmd, CustomEntityState, EntityStatePlayer, EntityState, ClientData];

    public static DeltaType? Find(string name)
    {
        foreach (var dt in All)
            if (dt.DeltaName == name)
                return dt;
        return null;
    }
}
